DROP DATABASE IF EXISTS gsp;
DROP DATABASE IF EXISTS AirSerbia;
DROP DATABASE IF EXISTS uns;
DROP DATABASE IF EXISTS muzicka;
DROP DATABASE IF EXISTS nekretnine;

CREATE DATABASE IF NOT EXISTS gsp CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS AirSerbia CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS uns CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS muzicka CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS nekretnine CHARACTER SET 'utf8';

USE gsp;
CREATE TABLE IF NOT EXISTS stanica (
  rbr INT UNIQUE AUTO_INCREMENT,
  lokacija VARCHAR(30),
  naziv VARCHAR(30),
  PRIMARY KEY (rbr)
);
CREATE TABLE IF NOT EXISTS linija (
  oznaka VARCHAR(5),
  poc_stanica INT,
  kraj_stanica INT,
  PRIMARY KEY (oznaka),
  CONSTRAINT FOREIGN KEY (poc_stanica) REFERENCES stanica(rbr),
  CONSTRAINT FOREIGN KEY (kraj_stanica) REFERENCES stanica(rbr)
);
CREATE TABLE IF NOT EXISTS vozac (
  id INT UNIQUE AUTO_INCREMENT,
  ime VARCHAR(30),
  prezime VARCHAR(30),
  br_licne_karte INT UNIQUE,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS autobus (
  reg_br INT UNIQUE AUTO_INCREMENT,
  br_sedista INT,
  PRIMARY KEY (reg_br)
);
CREATE TABLE IF NOT EXISTS zaduzenje (
  id_vozaca INT UNIQUE,
  oznaka_lin VARCHAR(5),
  reg_br INT UNIQUE,
  CONSTRAINT FOREIGN KEY (id_vozaca) REFERENCES vozac(id),
  CONSTRAINT FOREIGN KEY (reg_br) REFERENCES autobus(reg_br)
);
